"""
Translation catalog supporting English ('en'), Hindi ('hi'), and Tamil ('ta').
Covers all UI headings, sidebar controls, buttons, status banners, alerts, and TTS output.
"""

TRANSLATIONS = {
    "en": {
        "app_title": "AssistHands - Inclusive Rural Banking",
        "app_subtitle": "Accessible Financial Services for Rural Communities",
        "wallet_balance": "Account Balance",
        "setup_title": "🌾 Rural Banking Setup",
        "wallet_editor": "💳 Wallet Balance Editor",
        "set_exact_balance": "Set Exact Wallet Balance (₹):",
        "quick_add_funds": "Quick Add Funds:",
        "financial_baseline": "💰 Household Financial Baseline",
        "typical_spend": "Typical Spend Baseline (₹):",
        "income_cycle": "Primary Income Cycle:",
        "connection_status": "📡 Connection Status",
        "simulate_offline": "Simulate Offline Mode",
        "status_online_badge": "🟢 Connection: ONLINE (Live Voice active)",
        "status_offline_badge": "🔴 Connection: OFFLINE",
        "voice_command_title": "🎙️ Voice Assistant",
        "tap_to_speak_caption": "Tap the microphone button to speak your request, or type in the box below.",
        "tap_to_speak": "🔴 Tap to Speak",
        "or_type_phrase": "⌨️ Or Type Phrase",
        "type_placeholder": "e.g. Send 450 rupees to Local Kirana Store",
        "quick_actions_title": "🔘 Visual Quick Actions (Touch to Pay or Check)",
        "pay_kirana": "💸 Pay ₹450\n(Kirana)",
        "pay_milk": "🥛 Pay ₹1200\n(Milk Co-op)",
        "pay_seeds": "🌱 Pay ₹1500\n(Seeds/Depot)",
        "hear_balance": "🪙 Hear Balance\n(Audio Out)",
        "test_scam": "⚠️ Test Scam\n(Lottery)",
        "analysis_title": "⚡ Transaction Intent & Risk Analysis",
        "safe_badge": "🟢 SAFE",
        "caution_badge": "🟧 CAUTION",
        "critical_badge": "🔴 HIGH RISK / SCAM DETECTED",
        "elder_analogy": "🗣️ Village Elder Analogy:",
        "confirm_payment_btn": "✅ Execute Payment of ₹{amount} Now",
        "proceed_risk_btn": "⚠️ Proceed Risk Payment ₹{amount}",
        "cancel_payment_btn": "❌ Cancel Payment",
        "direct_form_title": "💸 Direct Manual Payment Form (Quick Transfer)",
        "recent_txns_title": "📜 Recent Transactions Log",
        "offline_queue_title": "📡 Offline Voice Queue",
        "sync_now_btn": "Sync Queue Now 🔄",
        "label_recipient": "Recipient",
        "label_amount": "Amount",
        "label_category": "Category / Purpose",
        "clarification_missing": "Could not parse transaction details. Please specify recipient and amount clearly (e.g. 'Send 1500 rupees to Fertilizer Depot').",
        "queued_items": "Queued Items",
        "listen_btn": "🔊 Listen",
        "demo_guide_title": "📋 Demo & Evaluation Guide",
        "demo_step1": "1. Reset Profile: Click 'Restart Voice Setup Wizard' in sidebar to test the 100% zero-text voice onboarding flow.",
        "demo_step2": "2. Test Offline Sync: Toggle 'Simulate Offline Mode' to ON -> record a voice payment -> check offline queue -> toggle OFF to see automatic reactive queue flushing with audio toast.",
        "demo_step3": "3. Test Risk Engine: Try a safe payment (₹450 Kirana) vs an anomaly spike (₹45,000 lottery scam) to see financial-pattern risk evaluation.",
        "demo_step4": "4. Test Household Verification: Set role to Youth -> request ₹2,500 payment -> switch role to Elder -> enter PIN 1234 to approve.",
    },
    "hi": {
        "app_title": "असिस्टहैंड्स - ग्रामीण समावेशी बैंकिंग",
        "app_subtitle": "ग्रामीण समुदायों के लिए सुलभ वित्तीय सेवाएं",
        "wallet_balance": "खाता शेष",
        "setup_title": "🌾 ग्रामीण बैंकिंग सेटअप",
        "wallet_editor": "💳 वॉलेट बैलेंस संपादक",
        "set_exact_balance": "सटीक वॉलेट बैलेंस दर्ज करें (₹):",
        "quick_add_funds": "त्वरित फंड जोड़ें:",
        "financial_baseline": "💰 घरेलू वित्तीय आधार",
        "typical_spend": "सामान्य खर्च सीमा (₹):",
        "income_cycle": "प्राथमिक आय चक्र:",
        "connection_status": "📡 कनेक्शन स्थिति",
        "simulate_offline": "ऑफ़लाइन मोड का अनुकरण करें",
        "status_online_badge": "🟢 कनेक्शन: ऑनलाइन (आवाज सक्रिय)",
        "status_offline_badge": "🔴 कनेक्शन: ऑफ़लाइन",
        "voice_command_title": "🎙️ वॉयस सहायक",
        "tap_to_speak_caption": "अपनी बात कहने के लिए माइक बटन दबाएं, या नीचे लिखें।",
        "tap_to_speak": "🔴 बोलने के लिए दबाएं",
        "or_type_phrase": "⌨️ या वाक्य लिखें",
        "type_placeholder": "जैसे 'किराना दुकान को 450 रुपये भेजें'",
        "quick_actions_title": "🔘 त्वरित कार्य (भुगतान या जांच के लिए छुएं)",
        "pay_kirana": "💸 ₹450 दें\n(किराना)",
        "pay_milk": "🥛 ₹1200 दें\n(डेयरी)",
        "pay_seeds": "🌱 ₹1500 दें\n(खाद/बीज)",
        "hear_balance": "🪙 बैलेंस सुनें\n(आवाज)",
        "test_scam": "⚠️ स्कैम जांच\n(लॉटरी)",
        "analysis_title": "⚡ लेन-देन विश्लेषण एवं जोखिम जांच",
        "safe_badge": "🟢 सुरक्षित",
        "caution_badge": "🟧 सावधान",
        "critical_badge": "🔴 उच्च जोखिम / घोटाला पाया गया",
        "elder_analogy": "🗣️ गाँव के बुजुर्ग की सलाह:",
        "confirm_payment_btn": "✅ अभी ₹{amount} का भुगतान करें",
        "proceed_risk_btn": "⚠️ जोखिम के बावजूद ₹{amount} भेजें",
        "cancel_payment_btn": "❌ भुगतान रद्द करें",
        "direct_form_title": "💸 प्रत्यक्ष भुगतान फॉर्म",
        "recent_txns_title": "📜 हाल के लेन-देन रिकॉर्ड",
        "offline_queue_title": "📡 ऑफ़लाइन वॉयस कतार",
        "sync_now_btn": "कतार अभी सिंक करें 🔄",
        "label_recipient": "प्राप्तकर्ता",
        "label_amount": "राशि",
        "label_category": "श्रेणी / उद्देश्य",
        "clarification_missing": "लेन-देन विवरण की पहचान नहीं हो सकी। कृपया प्राप्तकर्ता और राशि स्पष्ट रूप से बताएं (जैसे 'खाद डिपो को 1500 रुपये भेजें')।",
        "queued_items": "कतारबद्ध आइटम",
        "listen_btn": "🔊 सुनें",
        "demo_guide_title": "📋 डेमो एवं मूल्यांकन गाइड",
        "demo_step1": "1. प्रोफाइल रीसेट: 100% वॉयस ऑनबोर्डिंग सेटअप का परीक्षण करने के लिए साइडबार में 'रीस्टार्ट वॉयस सेटअप' पर क्लिक करें।",
        "demo_step2": "2. ऑफ़लाइन सिंक: ऑफ़लाइन मोड चालू करें -> वॉयस कमांड दें -> कतार जांचें -> ऑटो-सिंक देखने के लिए ऑफ़लाइन बंद करें।",
        "demo_step3": "3. जोखिम जांच: सुरक्षित भुगतान (₹450) बनाम संदिग्ध ट्रांसफर (₹45,000 लॉटरी) का परीक्षण करें।",
        "demo_step4": "4. पारिवारिक सत्यापन: यूजर रोल 'Youth' चुनें -> ₹2,500 का अनुरोध करें -> 'Elder' रोल में बदलें और पिन 1234 दर्ज करके स्वीकृत करें।",
    },
    "ta": {
        "app_title": "அசிஸ்ட்ஹேண்ட்ஸ் - கிராமப்புற வங்கி சேவை",
        "app_subtitle": "கிராமப்புற சமூகங்களுக்கான எளிய நிதி சேவைகள்",
        "wallet_balance": "கணக்கு இருப்பு",
        "setup_title": "🌾 கிராமப்புற வங்கி அமைப்புகள்",
        "wallet_editor": "💳 பணப்பையின் இருப்பு திருத்தி",
        "set_exact_balance": "துல்லியமான பணப்பை இருப்பை அமைக்கவும் (₹):",
        "quick_add_funds": "வேகமாக பணம் சேர்க்க:",
        "financial_baseline": "💰 குடும்ப நிதி வரம்பு",
        "typical_spend": "வழக்கமான செலவு வரம்பு (₹):",
        "income_cycle": "முக்கிய வருமான சுழற்சி:",
        "connection_status": "📡 இணைப்பு நிலை",
        "simulate_offline": "ஆஃப்லைன் பயன்முறையை இயக்கவும்",
        "status_online_badge": "🟢 இணைப்பு: ஆன்லைன் (குரல் சேவை செயலில் உள்ளது)",
        "status_offline_badge": "🔴 இணைப்பு: ஆஃப்லைன்",
        "voice_command_title": "🎙️ குரல் உதவியாளர்",
        "tap_to_speak_caption": "உங்கள் கோரிக்கையை கூற ஒலிவாங்கி பொத்தானை அழுத்தவும் அல்லது கீழே தட்டச்சு செய்யவும்.",
        "tap_to_speak": "🔴 பேச தொடுங்கள்",
        "or_type_phrase": "⌨️ அல்லது சொற்றொடரை தட்டச்சு செய்க",
        "type_placeholder": "எ.கா 'மளிகைக் கடைக்கு 450 ரூபாய் அனுப்பு'",
        "quick_actions_title": "🔘 எளிய சேவைகள் (செலுத்த அல்லது பார்க்க தொடுங்கள்)",
        "pay_kirana": "💸 ₹450 அனுப்பு\n(மளிகை)",
        "pay_milk": "🥛 ₹1200 அனுப்பு\n(பால் சங்கம்)",
        "pay_seeds": "🌱 ₹1500 அனுப்பு\n(விதை/உரம்)",
        "hear_balance": "🪙 இருப்பைக் கேள்\n(குரல் ஒலி)",
        "test_scam": "⚠️ மோசடி சோதனை\n(லாட்டரி)",
        "analysis_title": "⚡ பரிவர்த்தனை பகுப்பாய்வு மற்றும் ஆபத்து சோதனை",
        "safe_badge": "🟢 பாதுகாப்பானது",
        "caution_badge": "🟧 எச்சரிக்கை",
        "critical_badge": "🔴 அதிக ஆபத்து / மோசடி கண்டறியப்பட்டது",
        "elder_analogy": "🗣️ கிராமப் பெரியவரின் உதாரணம்:",
        "confirm_payment_btn": "✅ இப்போதே ₹{amount} செலுத்துங்கள்",
        "proceed_risk_btn": "⚠️ ஆபத்தையும் தாண்டி ₹{amount} செலுத்து",
        "cancel_payment_btn": "❌ ரத்து செய்",
        "direct_form_title": "💸 நேரடி பணம் செலுத்தும் படிவம்",
        "recent_txns_title": "📜 சமீபத்திய பரிவர்த்தனை வரலாறு",
        "offline_queue_title": "📡 ஆஃப்லைன் குரல் வரிசை",
        "sync_now_btn": "வரிசையை இப்போதே புதுப்பி 🔄",
        "label_recipient": "பெறுநர்",
        "label_amount": "தொகை",
        "label_category": "பிரிவு / நோக்கம்",
        "clarification_missing": "பரிவர்த்தனை விவரங்களை கண்டறிய முடியவில்லை. பெறுநர் மற்றும் தொகையை தெளிவாக கூறவும் (எ.கா. 'உரக் கடைக்கு 1500 ரூபாய் அனுப்பு').",
        "queued_items": "வரிசையில் உள்ளவை",
        "listen_btn": "🔊 கேள்",
        "demo_guide_title": "📋 மதிப்பீட்டு வழிகாட்டி",
        "demo_step1": "1. சுயவிவரம் மீட்டமை: 100% குரல் வழி அமைப்பை சோதிக்க 'குரல் அமைப்பை மீண்டும் தொடங்கு' கிளிக் செய்யவும்.",
        "demo_step2": "2. ஆஃப்லைன் புதுப்பித்தல்: ஆஃப்லைன் முறையை ஆன் செய்க -> குரல் கட்டளை பேசுங்கள் -> ஆஃப்லைன் ஆஃப் செய்து தானியங்கி புதுப்பிப்பை பாருங்கள்.",
        "demo_step3": "3. ஆபத்து சோதனைகள்: பாதுகாப்பான பரிவர்த்தனை (₹450) மற்றும் மோசடி பரிவர்த்தனை (₹45,000 லாட்டரி) சோதிக்கவும்.",
        "demo_step4": "4. குடும்ப சரிபார்ப்பு: 'Youth' தேர்வு செய்க -> ₹2,500 கோரிக்கை செய்க -> 'Elder' கணக்கிற்கு மாறி 1234 PIN உள்ளிட்டு ஒப்புதல் அளிக்கவும்.",
    }
}


def get_text(key: str, lang: str = "en") -> str:
    """Retrieve translated string for a given key and language. Falls back to English if key missing."""
    lang_catalog = TRANSLATIONS.get(lang, TRANSLATIONS["en"])
    return lang_catalog.get(key, TRANSLATIONS["en"].get(key, key))


def t(key: str, lang: str = "en") -> str:
    """Shorthand helper for get_text."""
    return get_text(key, lang)

